// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'pagenationSelect': string;
  'pagenationSelectDiv': string;
  'pagination': string;
  'paginationAlign': string;
  'paginationButtonActive': string;
  'paginationButtonClass': string;
  'paginationHide': string;
  'paginationNext': string;
  'paginationNextDiv': string;
  'paginationPageNum': string;
  'paginationPageNumNotAllowed': string;
  'paginationPrevious': string;
}
const cssExports: CssExports;
export default cssExports;
