/* tslint:disable */
require("./ApprovedList.module.css");
const styles = {
  leaveapproval: 'leaveapproval_aa46c408',
  searchLabel: 'searchLabel_aa46c408',
  LeaveDetailsNoRecord: 'LeaveDetailsNoRecord_aa46c408',
  highlight: 'highlight_aa46c408',
  leaveapprovalDiv1: 'leaveapprovalDiv1_aa46c408',
  leaveapprovalDropdown: 'leaveapprovalDropdown_aa46c408',
  leaveapprovalDropdownIcon: 'leaveapprovalDropdownIcon_aa46c408',
  leaveapprovalDropdownButton: 'leaveapprovalDropdownButton_aa46c408',
  leaveapprovalDropdownBlock: 'leaveapprovalDropdownBlock_aa46c408',
  leaveapprovalDropdownHidden: 'leaveapprovalDropdownHidden_aa46c408',
  leaveapprovalDropdownUl: 'leaveapprovalDropdownUl_aa46c408',
  leaveapprovalDropdownli: 'leaveapprovalDropdownli_aa46c408',
  leaveapprovalSearchBox: 'leaveapprovalSearchBox_aa46c408',
  leaveapprovalInput: 'leaveapprovalInput_aa46c408',
  leaveapprovalSearchButton: 'leaveapprovalSearchButton_aa46c408',
  leaveapprovalSearchIcon: 'leaveapprovalSearchIcon_aa46c408',
  leaveapprovalSearchSpan: 'leaveapprovalSearchSpan_aa46c408',
  leaveDetailsDiv1: 'leaveDetailsDiv1_aa46c408',
  LeaveDetailsNoRecordP: 'LeaveDetailsNoRecordP_aa46c408',
  leaveDetailsDiv2: 'leaveDetailsDiv2_aa46c408',
  leaveDetailsDiv3: 'leaveDetailsDiv3_aa46c408',
  leaveDetailsDiv4: 'leaveDetailsDiv4_aa46c408',
  leaveDetailsDiv5: 'leaveDetailsDiv5_aa46c408',
  leaveDetailsDiv6: 'leaveDetailsDiv6_aa46c408',
  leaveDetailsTable: 'leaveDetailsTable_aa46c408',
  leaveDetailsTableHead: 'leaveDetailsTableHead_aa46c408',
  leaveDetailsTableHeadSection: 'leaveDetailsTableHeadSection_aa46c408',
  leaveDetailTableHeadDiv: 'leaveDetailTableHeadDiv_aa46c408',
  leaveDetailTableHeadPara: 'leaveDetailTableHeadPara_aa46c408',
  leaveDetailTableHeadIcon: 'leaveDetailTableHeadIcon_aa46c408',
  leaveDetailsTableBody: 'leaveDetailsTableBody_aa46c408',
  leaveDetailsTableRow: 'leaveDetailsTableRow_aa46c408',
  leaveDetailsDescription: 'leaveDetailsDescription_aa46c408',
  leaveStatusPending: 'leaveStatusPending_aa46c408',
  leaveStatusApprove: 'leaveStatusApprove_aa46c408',
  leaveStatusCancel: 'leaveStatusCancel_aa46c408',
  leaveStatusSpan: 'leaveStatusSpan_aa46c408',
  leaveStatusReject: 'leaveStatusReject_aa46c408',
  leaveApprovalButtonDiv: 'leaveApprovalButtonDiv_aa46c408',
  leaveApprovalDate: 'leaveApprovalDate_aa46c408',
  leaveApprovalViewButton: 'leaveApprovalViewButton_aa46c408',
  leaveRejectButton: 'leaveRejectButton_aa46c408',
  topSection: 'topSection_aa46c408',
  closeButton: 'closeButton_aa46c408',
  export: 'export_aa46c408',
  headSection: 'headSection_aa46c408',
  Heads: 'Heads_aa46c408',
  exportButton: 'exportButton_aa46c408',
  exportButtonText: 'exportButtonText_aa46c408',
  exportButtonName: 'exportButtonName_aa46c408',
  tableRow: 'tableRow_aa46c408',
  exportOptions: 'exportOptions_aa46c408',
  defaultLop: 'defaultLop_aa46c408',
  totalLeaveCloseButton: 'totalLeaveCloseButton_aa46c408',
  LoaderDivision: 'LoaderDivision_aa46c408',
  loader: 'loader_aa46c408',
  spin: 'spin_aa46c408',
  exportButtonIcon: 'exportButtonIcon_aa46c408',
  fromDate: 'fromDate_aa46c408',
  toDate: 'toDate_aa46c408',
  leaveDetail: 'leaveDetail_aa46c408'
};

export default styles;
/* tslint:enable */