// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'Heads': string;
  'LeaveDetailsNoRecord': string;
  'LeaveDetailsNoRecordP': string;
  'LoaderDivision': string;
  'closeButton': string;
  'defaultLop': string;
  'export': string;
  'exportButton': string;
  'exportButtonIcon': string;
  'exportButtonName': string;
  'exportButtonText': string;
  'exportOptions': string;
  'fromDate': string;
  'headSection': string;
  'highlight': string;
  'leaveApprovalButtonDiv': string;
  'leaveApprovalDate': string;
  'leaveApprovalViewButton': string;
  'leaveDetail': string;
  'leaveDetailTableHeadDiv': string;
  'leaveDetailTableHeadIcon': string;
  'leaveDetailTableHeadPara': string;
  'leaveDetailsDescription': string;
  'leaveDetailsDiv1': string;
  'leaveDetailsDiv2': string;
  'leaveDetailsDiv3': string;
  'leaveDetailsDiv4': string;
  'leaveDetailsDiv5': string;
  'leaveDetailsDiv6': string;
  'leaveDetailsTable': string;
  'leaveDetailsTableBody': string;
  'leaveDetailsTableHead': string;
  'leaveDetailsTableHeadSection': string;
  'leaveDetailsTableRow': string;
  'leaveRejectButton': string;
  'leaveStatusApprove': string;
  'leaveStatusCancel': string;
  'leaveStatusPending': string;
  'leaveStatusReject': string;
  'leaveStatusSpan': string;
  'leaveapproval': string;
  'leaveapprovalDiv1': string;
  'leaveapprovalDropdown': string;
  'leaveapprovalDropdownBlock': string;
  'leaveapprovalDropdownButton': string;
  'leaveapprovalDropdownHidden': string;
  'leaveapprovalDropdownIcon': string;
  'leaveapprovalDropdownUl': string;
  'leaveapprovalDropdownli': string;
  'leaveapprovalInput': string;
  'leaveapprovalSearchBox': string;
  'leaveapprovalSearchButton': string;
  'leaveapprovalSearchIcon': string;
  'leaveapprovalSearchSpan': string;
  'loader': string;
  'searchLabel': string;
  'spin': string;
  'tableRow': string;
  'toDate': string;
  'topSection': string;
  'totalLeaveCloseButton': string;
}
const cssExports: CssExports;
export default cssExports;
