// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'Cancel': string;
  'activeLink': string;
  'normalLink': string;
  'sidebar': string;
  'sidebarDetail': string;
  'sidebarHeading': string;
  'sidebarImage': string;
  'sidebarLink': string;
  'sidebarLinks': string;
  'sidebarScroll': string;
  'sidebarSpan': string;
  'sidebarTitle': string;
}
const cssExports: CssExports;
export default cssExports;
