// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'CancelReasonTextarea': string;
  'CloseButton': string;
  'LeaveDetailsNoRecord': string;
  'LoaderDivision': string;
  'align': string;
  'applyLeaveButton': string;
  'applyLeaveButtonDiv': string;
  'button': string;
  'buttonSubmit': string;
  'cancelReason': string;
  'cancelReasonDiv1': string;
  'cancelReasonDiv2': string;
  'cancelReasonTextarea': string;
  'error': string;
  'header': string;
  'headerDiv': string;
  'inputContainer': string;
  'leaveCancelButton': string;
  'leaveDate': string;
  'leaveDateDiv': string;
  'leaveDetail': string;
  'leaveDetailsTableHeadSection': string;
  'leaveStatusApprove': string;
  'leaveStatusCancel': string;
  'leaveStatusPeanding': string;
  'leaveStatusReject': string;
  'leaveStatusSpan': string;
  'leaveTable': string;
  'loader': string;
  'spin': string;
  'tableBody': string;
  'tableBodyRow': string;
  'tableDescription': string;
  'tableDetail': string;
  'tableHead': string;
  'tableNorecord': string;
  'tableNorecordPara': string;
}
const cssExports: CssExports;
export default cssExports;
