// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'ApplyLeave': string;
  'ApplyLeave_form': string;
  'ApplyLeave_form_heading': string;
  'ApplyLeave_form_heading_name': string;
  'ApplyLeave_form_input': string;
  'ApplyLeave_form_label': string;
  'ApplyLeave_form_layout': string;
  'ApplyLeave_form_leaveInput': string;
  'ApplyLeave_form_leaveInput_desc': string;
  'ApplyLeave_form_leaveInput_svg': string;
  'button': string;
  'buttonSubmit': string;
  'error': string;
  'errorBorder': string;
  'errorSection': string;
  'formAlign': string;
  'input': string;
}
const cssExports: CssExports;
export default cssExports;
