// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

export interface CssExports {
  'profileSection': string;
  'icon': string;
  'md ': string;
  'text': string;
}

export default CssExports;
