// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'ApprovalLeaveTextarea': string;
  'LeaveDetailsNoRecord': string;
  'LoaderDivision': string;
  'ShowLess': string;
  'approvalLeave': string;
  'approvalLeaveDiv1': string;
  'approvalTable': string;
  'approvalTableDescription': string;
  'approvalTableHead': string;
  'approvalTableHeading': string;
  'approveButton': string;
  'approveButtonDiv': string;
  'button': string;
  'clickHere': string;
  'error': string;
  'errorBorder': string;
  'leaveApprovalButtonDiv': string;
  'leaveApprovalButtonDiv1': string;
  'leaveApprovalButtonDiv2': string;
  'leaveDetailsDescription': string;
  'loader': string;
  'reason': string;
  'scrollable': string;
  'spin': string;
  'totalLeave': string;
  'totalLeaveCloseButton': string;
  'totalLeaveDiv1': string;
  'totalLeaveDiv2': string;
  'totalLeaveHeader': string;
  'totalLeaveHeaderDiv': string;
  'totalLeaveTableContainer': string;
}
const cssExports: CssExports;
export default cssExports;
