// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'approvalTable': string;
  'approvalTableDescription': string;
  'approvalTableHead': string;
  'approvalTableHeading': string;
  'approveButton': string;
  'approveButtonDiv': string;
  'totalLeave': string;
  'totalLeaveCloseButton': string;
  'totalLeaveDiv1': string;
  'totalLeaveDiv2': string;
  'totalLeaveHeader': string;
  'totalLeaveHeaderDiv': string;
  'totalLeaveTableContainer': string;
}
const cssExports: CssExports;
export default cssExports;
