// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'leaveApprovalButtonDiv': string;
  'leaveApprovalDate': string;
  'leaveApprovalViewButton': string;
  'leaveDetailTableHeadDiv': string;
  'leaveDetailTableHeadIcon': string;
  'leaveDetailTableHeadPara': string;
  'leaveDetailsDescrition': string;
  'leaveDetailsDiv1': string;
  'leaveDetailsDiv2': string;
  'leaveDetailsDiv3': string;
  'leaveDetailsDiv4': string;
  'leaveDetailsDiv5': string;
  'leaveDetailsDiv6': string;
  'leaveDetailsTable': string;
  'leaveDetailsTableBody': string;
  'leaveDetailsTableHead': string;
  'leaveDetailsTableRow': string;
  'leaveRejectButton': string;
  'leaveStatusApprove': string;
  'leaveStatusCancel': string;
  'leaveStatusPending': string;
  'leaveStatusReject': string;
  'leaveStatusSpan': string;
  'leaveapproval': string;
  'leaveapprovalDiv1': string;
  'leaveapprovalDropdown': string;
  'leaveapprovalDropdownBlock': string;
  'leaveapprovalDropdownButton': string;
  'leaveapprovalDropdownHidden': string;
  'leaveapprovalDropdownIcon': string;
  'leaveapprovalDropdownUl': string;
  'leaveapprovalDropdownli': string;
  'leaveapprovalInput': string;
  'leaveapprovalSearchBox': string;
  'leaveapprovalSearchButton': string;
  'leaveapprovalSearchIcon': string;
  'leaveapprovalSearchSpan': string;
}
const cssExports: CssExports;
export default cssExports;
