// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'publicHolidaysSection': string;
  'publicHolidaysSection_one': string;
  'publicHolidaysSection_one_Table': string;
  'publicHolidaysSection_one_Table_tbody': string;
  'publicHolidaysSection_one_Table_tbody_td': string;
  'publicHolidaysSection_one_Table_th': string;
  'publicHolidaysSection_one_Table_th_max': string;
  'publicHolidaysTitle': string;
}
const cssExports: CssExports;
export default cssExports;
