// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'circle': string;
  'email': string;
  'info': string;
  'initials': string;
  'navbarButton': string;
  'navbarButtonIcon': string;
  'navbarHeader': string;
  'navbarSection': string;
  'navbarSectionOne': string;
  'profile_photo': string;
}
const cssExports: CssExports;
export default cssExports;
