// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'Table': string;
  'TableBodyDescription': string;
  'TableBodyHead': string;
  'TableHead': string;
  'TableHeaderHeading': string;
  'TableHeaderHeadingDiv': string;
  'approvalTableDescription': string;
  'totalLeave': string;
  'totalLeaveCloseButton': string;
  'totalLeaveDiv1': string;
  'totalLeaveDiv2': string;
  'totalLeaveHeader': string;
  'totalLeaveHeaderDiv': string;
  'totalLeaveTableContainer': string;
}
const cssExports: CssExports;
export default cssExports;
