// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'ApplyLeave_form_input': string;
  'Head': string;
  'button': string;
  'buttonSubmit': string;
  'defaultLop': string;
  'error': string;
  'errorBorder': string;
  'errorSection': string;
  'inputContainer': string;
  'lop': string;
  'lopNumber': string;
}
const cssExports: CssExports;
export default cssExports;
