// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'components': string;
  'mainSection': string;
  'navbar': string;
  'navbar_section': string;
  'navbar_section_1': string;
  'section': string;
  'sideBar': string;
  'sideBar1': string;
}
const cssExports: CssExports;
export default cssExports;
